services:
  _defaults:
    autowire: true
    autoconfigure: true

  FSchmidDev\LeafletMapBundle\EventListener\Widget\LocationListener:
    class: FSchmidDev\LeafletMapBundle\EventListener\Widget\LocationListener
