services:
  _defaults:
    autowire: true
    autoconfigure: true

  FSchmidDev\LeafletMapBundle\FrontendModule\LeafletMapModule:
    class: FSchmidDev\LeafletMapBundle\FrontendModule\LeafletMapModule